using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CompiladorV1.Transversal
{
    public enum Categoria
    {
        SUMA,VARIABLE,PALABRA_RESERVADA_INT, PALABRA_RESERVADA_ON, PALABRA_RESERVADA_OFF,MODULO, PARENTESIS_ABRE,PARENTESIS_CIERRA,RESTA,MULTIPLICACION,DIVISION,IGUAL_QUE, MAYOR_QUE,MENOR_QUE,ENTERO,DECIMAL,IDENTIFICADOR,DIFERENTE,MENOR_O_IGUAL_QUE,MAYOR_O_IGUAL_QUE,ASIGNACION,CARACTER_NO_VALIDO,FIN_ARCHIVO
    }

   
}
